export const tablaCartas = {
  "1": {
    "angel": "Vehuiah",
    "imagen": "",
    "atributo": "Dios elevado por encima de todas las cosas",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 12:00 a.m. a 12:20 a.m",
    "se canaliza para": "Emprender y ejecutar las cosas más difíciles. transformarse en un guerrero del fuego espiritual",
    "color": "Azul claro",
    "columna1": "Vehuiah",
    "por fecha de nac": "20 al 24 de marzo",
    "mensaje": "Nos encamina a nuestro destino.Dota de energia cuando mas lo necesitamos"
  },
  "2": {
    "angel": "Jeliel",
    "imagen": "",
    "atributo": "Dios que socorre",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 12:20 a.m a 12:40 a.m",
    "se canaliza para": "Conseguir victoria contra quienes nos atacan injustamente. calma revueltas populares y mejora el comportamiento de los gobernantes. restablece la paz entre los esposos y la fidelidad conyugal. restablece la armonía entre empleados y empleadores",
    "color": "rojo",
    "columna1": "Jeliel",
    "por fecha de nac": "25 al 29 de marzo",
    "mensaje": "Proporciona amor y sabiduria en nuestras vidas. Tiene como mision difundir el amor en todas sus formas"
  },
  "3": {
    "angel": "Sitael",
    "imagen": "",
    "atributo": "Dios esperanza de todas las criaturas",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 12:40 a.m a 1:00 a.m",
    "se canaliza para": "Calmarnos ante las adversidades. protegernos en accidentes de automóviles y asaltos. darnos fuerza y voluntad ante nuestros compromisos. pedir protección ante todo tipo de ataque",
    "color": "azul",
    "columna1": "Sitael",
    "por fecha de nac": "30 de marzo al 3 de abril",
    "mensaje": "Su mision es ayudarnos a alcanzar el éxito y a cumplir nuestros sueños"
  },
  "4": {
    "angel": "Elemiah",
    "imagen": "",
    "atributo": "Dios Oculto",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 1:00 a.m a 1:20 a.m",
    "se canaliza para": "Aquietar el espíritu atormentado ante las adversidades. reconsiderar nuestros actos. protección en los viajes. ayudarnos a conocer a los traidores. ayudarnos a descubrir la profesión. que nos ilumine para no continuar en los errores",
    "color": "rojo",
    "columna1": "Elemiah",
    "por fecha de nac": "4 al 8 de abril",
    "mensaje": "Puedes acudir a él cada que necesites saber cuál es el camino correcto en tu vida"
  },
  "5": {
    "angel": "Mahasiah",
    "imagen": "",
    "atributo": "Dios Salvador",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 1:20 a.m a 1:40 a.m",
    "se canaliza para": "Vivir en paz con todo el mundo. obtener fuerza moral. concedernos el conocimiento de las ciencias del espíritu. comprender sobre filosofía y teología",
    "color": "amarillo",
    "columna1": "Mahasiah",
    "por fecha de nac": "9 al 13 de abril",
    "mensaje": "Es el guia y ayudante de los estudiantes"
  },
  "6": {
    "angel": "Lelahel",
    "imagen": "",
    "atributo": "Dios Loable",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 1:40 a.m a 2:00 a.m",
    "se canaliza para": "Curar enfermedades del espíritu. no tener ambición desmedida y no utilizar el poder para fines ilícitos. ayudarnos a reflexionar. adquirir iluminación y protegernos de personas malvadas",
    "color": "verde",
    "columna1": "Lelahel",
    "por fecha de nac": "14 al 18 de abril",
    "mensaje": "Aclara todas tus dudas y enseña a mirar en nuestro interior"
  },
  "7": {
    "angel": "Achaiah",
    "imagen": "",
    "atributo": "Dios Paciente",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 2:00 a.m a 2:20 a.m",
    "se canaliza para": "Propagar nuevas ideas, brindarnos la capacidad de ser pacientes, encontrar el sentido de la vida cuando se pierde la fe, pedirle ayuda para encontrar éxito en tareas difíciles, facilitarnos el descubrir secretos de la naturaleza",
    "color": "Naranja",
    "columna1": "Achaiah",
    "por fecha de nac": "19 al 23 de abril",
    "mensaje": "Otorga la sagrada paciencia cuando atravesamos momentos dificiles en nuestra vida"
  },
  "8": {
    "angel": "Cahetel",
    "imagen": "",
    "atributo": "Dios Adorable",
    "planeta": "Neptuno",
    "coro angelical": "Serafines",
    "aroma": "Flores blancas, Jazminez y Camelias",
    "talisman": "Espejos",
    "ofrenda": "Cuentos Infantiles y Gemas Naranjas",
    "don ser de luz": "Fortaleza y fe en Dios",
    "hora canalizacion": "de 2:20 a.m a 2:40 a.m",
    "se canaliza para": "Protección de personas y cosas, expulsar malos espíritus o pensamientos negativos obsesivos, obtener misericordia y bendición de dios, agradecer los bienes de consumo obtenidos de la tierra, favorecer la producción agrícola",
    "color": "Violeta",
    "columna1": "Cahetel",
    "por fecha de nac": "24 al 28 de abril",
    "mensaje": "Es el ángel de los cambios en la vida. Invocalo cuando necesites un verdadero cambio"
  },
  "9": {
    "angel": "Haziel",
    "imagen": "",
    "atributo": "Dios Misericordia",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 2:40 a.m a 3:00 a.m",
    "se canaliza para": "Dar y recibir bondad, conseguir el cumplimiento de una promesa, recibir apoyo de los demás y misericordia divina, tener buenas amistades, reconciliación",
    "color": "verde claro",
    "columna1": "Haziel",
    "por fecha de nac": "29 de abril al 3 de mayo",
    "mensaje": "Trae el perdon y la reconciliación en tu vida"
  },
  "10": {
    "angel": "Aladiah",
    "imagen": "",
    "atributo": "Dios Propicio",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 3:00 a.m a 3:20 a.m",
    "se canaliza para": "Sanar dolencias físicas y espirituales, protegernos de energías psíquicas nocivas y envidias proyectadas hacia uno, obtener perdón cuando hay real arrepentimiento, regeneración de la moral, gozar de la amistad de personas importantes",
    "color": "rojo",
    "columna1": "Aladiah",
    "por fecha de nac": "4 al 8 de mayo",
    "mensaje": "Es el portador de segundas oportunidades y tiene una capacidad de sanación"
  },
  "11": {
    "angel": "Loviah",
    "imagen": "",
    "atributo": "Dios Exaltado",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 3:20 a.m a 3:40 a.m",
    "se canaliza para": "Prevenir ataques de nervios, protección contra rayos y tempestades naturales, protección contra el orgullo y la calumnia, obtener victoria sobre los adversarios, sobreponernos a nuestras debilidades, rehacer amistades, protegernos de fraudes",
    "color": "Plata",
    "columna1": "Lauviah",
    "por fecha de nac": "9 al 13 de mayo",
    "mensaje": "Ayuda a desarrollar tu intuición en el mundo terrenal y espirutual"
  },
  "12": {
    "angel": "Hahahiah",
    "imagen": "",
    "atributo": "Dios Refugio",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 3:40 a.m a 4:00 a.m",
    "se canaliza para": "Interpretar sueños y misterios ocultos, brindarnos ayuda ante adversidades en general, protegernos contra la mentira y el abuso de confianza, brindar revelaciones en especial sobre cosmología",
    "color": "Violeta",
    "columna1": "Hahahiah",
    "por fecha de nac": "14 al 18 de mayo",
    "mensaje": "Te enseña a marte a ti mismo y a meditar"
  },
  "13": {
    "angel": "Lezalel",
    "imagen": "",
    "atributo": "Dios Glorificado",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 4:00 a.m a 4:20 a.m",
    "se canaliza para": "Obtener justicia. liberar de la depresión. favorecer la imparcialidad de los magistrados. proteger contra la calumnia y falsos testimonios de aquellos que desean usurpar los bienes ajenos. proteger a los inocentes y hacer conocer la verdad",
    "color": "Azul",
    "columna1": "Lezalel",
    "por fecha de nac": "19 al 23 de mayo",
    "mensaje": "Aporta reconciliación y afinidad cuando tienes problemas en una relacion"
  },
  "14": {
    "angel": "Mebahel",
    "imagen": "",
    "atributo": "Dios Conservador",
    "planeta": "Saturno",
    "coro angelical": "Tronos",
    "aroma": "Flores de Lavanda",
    "talisman": "Cristales",
    "ofrenda": "Flores de Lavanda",
    "don ser de luz": "Conocimiento sobre el mundo visible e invisible",
    "hora canalizacion": "de 4:20 a.m a 4:40 a.m",
    "se canaliza para": "Pedir justicia e imparcialidad. pedir protección contra la calumnia y falsos testimonios de aquellos que desean usurpar los bienes ajenos. liberarnos de la depresión. proteger a los inocentes. hacer conocer la verdad",
    "color": "Azul",
    "columna1": "Mebahel",
    "por fecha de nac": "24 al 28 de mayo",
    "mensaje": "Es el gran protector de la verdad, la justicia, la libertad y el compromiso"
  },
  "15": {
    "angel": "Hariel",
    "imagen": "",
    "atributo": "Dios Creador",
    "planeta": "Saturno",
    "coro angelical": "Tronos",
    "aroma": "Flores de Lavanda",
    "talisman": "Cristales",
    "ofrenda": "Flores de Lavanda",
    "don ser de luz": "Conocimiento sobre el mundo visible e invisible",
    "hora canalizacion": "de 4:40 a.m a 5:00 a.m",
    "se canaliza para": "Obtener mejoras en el desempeño profesional. atraer el amor y la bondad de quienes nos rodean, especialmente entre los integrantes de nuestras familias. exaltar los sentimientos religiosos. ayudarnos a descubrir lo útil y lo bueno",
    "color": "Naranja",
    "columna1": "Hariel",
    "por fecha de nac": "29 de mayo al 3 de junio",
    "mensaje": "Ayuda a las personas a deshacerse de adicciones y dependencias"
  },
  "16": {
    "angel": "Hekamiah",
    "imagen": "",
    "atributo": "Dios Creador del Universo",
    "planeta": "Saturno",
    "coro angelical": "Tronos",
    "aroma": "Flores de Lavanda",
    "talisman": "Cristales",
    "ofrenda": "Flores de Lavanda",
    "don ser de luz": "Conocimiento sobre el mundo visible e invisible",
    "hora canalizacion": "de 5:00 a.m a 5:20 a.m",
    "se canaliza para": "Ayudarnos a trascender nuestros problemas. vencer a nuestros enemigos internos. proteger a los que ocupan posiciones de liderazgo. pedir coraje, perseverancia y constancia",
    "color": "Naranja",
    "columna1": "Hekamiah",
    "por fecha de nac": "4 al 8 de junio",
    "mensaje": "Enseña y proporciona lealtad según los principios divinos"
  },
  "17": {
    "angel": "Lauviah",
    "imagen": "",
    "atributo": "Dios Admirable",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 5:20 a.m a 5:40 a.m",
    "se canaliza para": "Generar amistades profundas. revelarnos el significado de los sueños. obtener talento artístico y literario. ayudarnos a salir de los tormentos espirituales y la tristeza. dormir bien. tener compresión de las ciencias espirituales",
    "color": "amarillo",
    "columna1": "Lauviah",
    "por fecha de nac": "9 al 13 de junio",
    "mensaje": "Es el ángel de la victoria y de las personas exitosas"
  },
  "18": {
    "angel": "Caliel",
    "imagen": "",
    "atributo": "Dios que escucha",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 5:40 a.m a 6:00 a.m",
    "se canaliza para": "Encontrar un buen defensor en los procesos judiciales. brindarnos socorro ante adversidades para que surjan las verdades en los procesos conflictivos",
    "color": "Dorado",
    "columna1": "Caliel",
    "por fecha de nac": "14 al 18 de junio",
    "mensaje": "Nos ayuda a comprender las diferencias entre el bien y el mal"
  },
  "19": {
    "angel": "Leuviah",
    "imagen": "",
    "atributo": "Dios Auxilio de los Pecadores",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 6:00 a.m a 6:20 a.m",
    "se canaliza para": "Brindarnos inspiración poética y artística. otorgarnos la gracia divina a la fecundidad. aumentar nuestra memoria y nuestra inteligencia",
    "color": "verde",
    "columna1": "Leuviah",
    "por fecha de nac": "19 al 23 de junio",
    "mensaje": "Guarda los recuerdos de tus vidas pasadas"
  },
  "20": {
    "angel": "Pahaliah",
    "imagen": "",
    "atributo": "Dios Redentor",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 6:20 a.m a 6:40 a.m",
    "se canaliza para": "Otorgarnos revelaciones de la verdad y sabiduría. ayudarnos a encontrar la vocación correcta",
    "color": "verde",
    "columna1": "Pahaliah",
    "por fecha de nac": "24 al 28 de junio",
    "mensaje": "Esel ángel de los que quieren deshacerce de viejos y malos comportamientos"
  },
  "21": {
    "angel": "Nelkhael",
    "imagen": "",
    "atributo": "Dios Unico",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 6:40 a.m a 7:00 a.m",
    "se canaliza para": "Destruir el poder del enemigo. protegernos contra calumnias y también de aquellas personas que intentan sacar provecho para sí de los inocentes. ayudarnos a comprender la astronomía, astrología, geología, matemáticas y ciencias exactas",
    "color": "Azul palido",
    "columna1": "Nelkhael",
    "por fecha de nac": "29 de junio al 3 de julio",
    "mensaje": "Es el ángel de los que tienen el ferviente deseo de aprender"
  },
  "22": {
    "angel": "Yeiyael",
    "imagen": "",
    "atributo": "Justicia Divina",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 7:00 a.m a 7:20 a.m",
    "se canaliza para": "Proteger los comercios. la protección de nuestra fama y fortuna. ayudarnos en los estudios que cursamos. descubrir la vocación y nuevos caminos",
    "color": "Amarillo",
    "columna1": "Yeiyael",
    "por fecha de nac": "4 al 8 de julio",
    "mensaje": "Trae el sentido del orden y de la disciplina a aquellos que más lo necesitan"
  },
  "23": {
    "angel": "Melahel",
    "imagen": "",
    "atributo": "Dios que Libera del Mal",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 7:20 a.m a 7:40 a.m",
    "se canaliza para": "Realizar nuestros deseos. protección en las actividades políticas y públicas. recibir abundancia por nuestro trabajo. protección contra armas y asaltos. potenciar el efecto de plantas medicinales",
    "color": "Azul",
    "columna1": "Melahel",
    "por fecha de nac": "9 al 13 de julio",
    "mensaje": "Tiene la capacidad de curación, por lo que protege a medicos y a todo aquel que se dedique a sanar a los demás"
  },
  "24": {
    "angel": "Haheuiah",
    "imagen": "",
    "atributo": "Dios Bondadoso por si mismo",
    "planeta": "Urano",
    "coro angelical": "Querubines",
    "aroma": "Rosas y fresas",
    "talisman": "Gemas Amarillas",
    "ofrenda": "Objetos Brillantes",
    "don ser de luz": "Iluminación y Sabiduria",
    "hora canalizacion": "de 7:40 a.m a 8:00 a.m",
    "se canaliza para": "Conseguir la gracia de dios. proteger a prisioneros, fugitivos, que sufren penas injustas. protegernos de ladrones y asesinos. protegernos contra accidentes de automovil y todo tipo de violencia",
    "color": "Plata",
    "columna1": "Haheuiah",
    "por fecha de nac": "14 al 18 de julio",
    "mensaje": "Aporta a los nacidos en estas fechas la virtud de la sinceridad y la verdad"
  },
  "25": {
    "angel": "Nith - Haiah",
    "imagen": "",
    "atributo": "Dios que da sabiduria",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 8:00 a.m a 8:20 a.m",
    "se canaliza para": "Obtener sabiduría y revelaciones de misterios ocultos. influenciar en la magia blanca para atraer nuevas revelaciones. obtener paz a través del conocimiento de la verdad",
    "color": "Indigo",
    "columna1": "Nith - Haiah",
    "por fecha de nac": "19 al 23 de julio",
    "mensaje": "Enseña a comprender y a utilizar correctamente las fuerzas espirituales"
  },
  "26": {
    "angel": "Haaiah",
    "imagen": "",
    "atributo": "Dios Oculto",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 8:20 a.m a 8:40 a.m",
    "se canaliza para": "Ayudarnos a ganar procesos judiciales. descubrir conspiraciones. ayudarnos a buscar la verdad para llevarnos a contemplar las cosas divinas",
    "color": "Violeta",
    "columna1": "Haaiah",
    "por fecha de nac": "24 al 28 de julio",
    "mensaje": "Guarda bien los secretos que no deben ser revelados"
  },
  "27": {
    "angel": "Yerathel",
    "imagen": "",
    "atributo": "Dios que castiga alos Malos",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 8:40 a.m a 9:00 a.m",
    "se canaliza para": "Pedir protección contra ataques injustos. darnos conocimiento de verdades divinas. tener éxito en los negocios. cortar la magia negra cuando es injusta",
    "color": "Azul",
    "columna1": "Yerathel",
    "por fecha de nac": "29 de julio al 2 de agosto",
    "mensaje": "Es el propagador de la luz divina"
  },
  "28": {
    "angel": "Seheiah",
    "imagen": "",
    "atributo": "Dios que cura las Enfermedades",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 9:00 a.m a 9:20 a.m",
    "se canaliza para": "Protegernos contra incendios, accidentes y dolencias. protegernos de la maldad y de la ruina en los negocios",
    "color": "Azul",
    "columna1": "Seheiah",
    "por fecha de nac": "3 al 7 de agosto",
    "mensaje": "Te protege de los accidentes, caídas, rayos, incendios o enfermedades"
  },
  "29": {
    "angel": "Reiyel",
    "imagen": "",
    "atributo": "Dios que socorre",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 9:20 a.m a 9:40 a.m",
    "se canaliza para": "Librarnos de los enemigos internos. darnos inspiración en oraciones y discursos. tener claridad de expresión ante los adversarios. realzar los sentimientos religiosos y la meditación",
    "color": "Naranja",
    "columna1": "Reiyel",
    "por fecha de nac": "8 al 13 de agosto",
    "mensaje": "Es capaz de liberarnos de cualquier fuerza maligna y hechicería"
  },
  "30": {
    "angel": "Omael",
    "imagen": "",
    "atributo": "Dios Paciente",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 9:40 a.m a 10:00 a.m",
    "se canaliza para": "Protección del reino animal. tener paciencia cuando estamos muy ansiosos. tener buena relación entre padres e hijos. que guie a nuestro médico cirujano",
    "color": "Naranja",
    "columna1": "Omael",
    "por fecha de nac": "14 al 18 de agosto",
    "mensaje": "Te ayuda a crear proyectos, expandir tus sueños y hacerlos realidad"
  },
  "31": {
    "angel": "Lecabel",
    "imagen": "",
    "atributo": "Dios Inspirar",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 10:00 a.m a 10:20 a.m",
    "se canaliza para": "Resolver temas en la profesión. resolver problemas muy difíciles. tener revelaciones",
    "color": "Dorado",
    "columna1": "Lecabel",
    "por fecha de nac": "19 al 23 de agosto",
    "mensaje": "Las personas que estén bajo su proteccion tratarán de alcanzar la perfección en sus vidas"
  },
  "32": {
    "angel": "Vasariah",
    "imagen": "",
    "atributo": "Dios Justo",
    "planeta": "Marte",
    "coro angelical": "Potestades",
    "aroma": "Incienso y Flores",
    "talisman": "Caracoles",
    "ofrenda": "Hojas de Pino, Esmeralda",
    "don ser de luz": "Control de los enemigos",
    "hora canalizacion": "de 10:20 a.m a 10:40 a.m",
    "se canaliza para": "Obtener justicia. tener buena memoria y facilidad de expresión. protegernos contra quien nos ataca judicialmente",
    "color": "Dorado",
    "columna1": "Vasariah",
    "por fecha de nac": "24 al 28 de agosto",
    "mensaje": "Ofrece sabiduría para la reflexión y encontrar la solución a los problemas"
  },
  "33": {
    "angel": "Yehuiah",
    "imagen": "",
    "atributo": "Dios Conocedor de todas las cosas",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 10:40 a.m a 11:00 a.m",
    "se canaliza para": "Poner en evidencia situaciones ocultas de conocer a las personas traidoras y conocer sus planes. traernos revelaciones sobre nuestros defectos y actitudes erradas",
    "color": "Verde",
    "columna1": "Yehuiah",
    "por fecha de nac": "29 de agosto al 2 de septiembre",
    "mensaje": "Enseña los beneficios de colaborar en equipo y a trabajar con otros fácilmente"
  },
  "34": {
    "angel": "Lehahiah",
    "imagen": "",
    "atributo": "Dios Clemente",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 11:00 a.m a 11:20 a.m",
    "se canaliza para": "Calmar nuestra ira. comprender las leyes divinas y la estructura del universo",
    "color": "Verde",
    "columna1": "Lehahiah",
    "por fecha de nac": "3 al 7 de septiembre",
    "mensaje": "Los nacidos bajo su signo seguirán las leyes de Dios, aunque no las entiendan"
  },
  "35": {
    "angel": "Chavakhiah",
    "imagen": "",
    "atributo": "Dios que da Alegría",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 11:20 a.m a 11:40 a.m",
    "se canaliza para": "Reconciliación entre familiares. obtener perdón por ofensas. la partición de herencias en forma justa. tener buena relación entre padres e hijos",
    "color": "Turquesa",
    "columna1": "Chavakhiah",
    "por fecha de nac": "8 al 12 de septiembre",
    "mensaje": "Es el ángel de la reconciliación por excelencia."
  },
  "36": {
    "angel": "Menadel",
    "imagen": "",
    "atributo": "Dios Digno de Admiración",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 11:40 a.m a 12:00 p.m",
    "se canaliza para": "Para mantenerse en los empleos. conservar lo que se tiene. encontrar objetos perdidos. protegernos contra calumnias y maldiciones. tener noticias sobre personas distantes",
    "color": "Gris",
    "columna1": "Menadel",
    "por fecha de nac": "13 al 17 de septiembre",
    "mensaje": "Puede ayudarnos a conseguir un mejor trabajo, que se adapte a lo que nosotros siempre hemos soñado."
  },
  "37": {
    "angel": "Aniel",
    "imagen": "",
    "atributo": "Dios Virtuoso",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 12:00 p.m a 12:20 p.m",
    "se canaliza para": "Para impulsarnos a resolver situaciones difíciles. promover la armonía entre personas diferentes. revelarnos secretos sobre la naturaleza. tener inspiración en conferencias y meditaciones. ayudarnos a que nos expresemos más fácilmente",
    "color": "verde",
    "columna1": "Aniel",
    "por fecha de nac": "18 al 22 de septiembre",
    "mensaje": "Se le relaciona con el dinero y el intercambio."
  },
  "38": {
    "angel": "Haamiah",
    "imagen": "",
    "atributo": "Dios Esperanza de Todos",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 12:20 p.m a 12:40 p.m",
    "se canaliza para": "Protegernos contra las armas de fuego. descubrir la verdad y proteger las obras espirituales",
    "color": "Plata",
    "columna1": "Haamiah",
    "por fecha de nac": "23 al 27 de septiembre",
    "mensaje": "Es el ángel de rituales, ceremonias y de los días mágicos."
  },
  "39": {
    "angel": "Rehael",
    "imagen": "",
    "atributo": "Dios que acoge a los Pecadores",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 12:40 p.m a 1:00 p.m",
    "se canaliza para": "Mantener la salud y la longevidad. protegernos contra la maldad. que podamos ver cuando actuamos erróneamente. influenciar en el amor paternal y filial y en la obediencia de los más pequeños con respecto a los mayores",
    "color": "Violeta",
    "columna1": "Rehael",
    "por fecha de nac": "28 septiembre al 2 de octubre",
    "mensaje": "Ayuda a entender las cosas con mayor profundidad."
  },
  "40": {
    "angel": "Yeiazel",
    "imagen": "",
    "atributo": "Dios que da Alegría",
    "planeta": "Jupiter",
    "coro angelical": "Dominaciones",
    "aroma": "Azahar y Limon",
    "talisman": "Limones",
    "ofrenda": "Cuarzo Rosado y Verde,Velas, incienso, Amatistas",
    "don ser de luz": "Perseverancia y Salvacion",
    "hora canalizacion": "de 1:00 p.m a 1:20 p.m",
    "se canaliza para": "Liberarnos de nuestra prisión interna. tener consuelo ante las adversidades. liberarnos de enemigos y vicios. liberarnos de la depresión y el pánico",
    "color": "Verde",
    "columna1": "Yeiazel",
    "por fecha de nac": "3 al 7 de octubre",
    "mensaje": "Trae consuelo a nuestras vidas, nos enseña a apreciar los tiempos de renovación"
  },
  "41": {
    "angel": "Hahahhel",
    "imagen": "",
    "atributo": "Dios en 3 personas (Dios Manifestado)",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 1:20 p.m a 1:40 p.m",
    "se canaliza para": "Tener firmeza en nuestra evolución. seguir la luz del amor. retornar a la fe de dios. protegernos contra las calamidades",
    "color": "Azul",
    "columna1": "Hahahhel",
    "por fecha de nac": "8 al 12 de octubre",
    "mensaje": "Nos ayuda a ser fieles en nuestra misión en la Tierra y despertando nuestra vocación espiritual."
  },
  "42": {
    "angel": "Mikael",
    "imagen": "",
    "atributo": "Quien como Dios",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 1:40 p.m a 2:00 p.m",
    "se canaliza para": "Tener seguridad en viajes. obtener obediencia o disciplina de los subalternos. extraer negatividad de personas, lugares o cosas. poner en evidencia todo lo oscuro",
    "color": "Azul",
    "columna1": "Mikael",
    "por fecha de nac": "13 al 17 de octubre",
    "mensaje": "Ayuda en las organizaciones, así como en la enseñanza del bien y el mal."
  },
  "43": {
    "angel": "Veuliah",
    "imagen": "",
    "atributo": "Dios Rey Dominante",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 2:00 p.m a 2:20 p.m",
    "se canaliza para": "Tener paz y prosperidad interior. destruir nuestros enemigos interiores, como por ejemplo los miedos. liberar de la esclavitud y de los vicios. tener éxito en causas justas. obtener favores de personas importantes. protección y prosperidad en empresas",
    "color": "Violeta",
    "columna1": "Veuliah",
    "por fecha de nac": "18 al 22 de octubre",
    "mensaje": "Es el ángel de la prosperidad, abundancia y riqueza para tu vida."
  },
  "44": {
    "angel": "Yelahiah",
    "imagen": "",
    "atributo": "Dios Eterno",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 2:20 p.m a 2:40 p.m",
    "se canaliza para": "Tener coraje para enfrentar las adversidades. proteger a magistrados para vencer en los procesos judiciales. protegernos contra armas blancas o de fuego",
    "color": "verde",
    "columna1": "Yelahiah",
    "por fecha de nac": "23 al 28 de octubre",
    "mensaje": "Es un guerrero de luz, por lo que es protector y guía celestial."
  },
  "45": {
    "angel": "Sealiah",
    "imagen": "",
    "atributo": "Dios Generador de todas las cosas",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 2:40 p.m a 3:00 p.m",
    "se canaliza para": "Tener buena salud y curarse de alguna enfermedad. exaltar a los humildes, separándolos de los orgullosos, es decir, cuando nos sentimos oprimidos por otro. ayudarnos en el aprendizaje de artes y ciencias para el bienestar de los hombres, plantas y animales",
    "color": "Dorado",
    "columna1": "Sealiah",
    "por fecha de nac": "29 de octubre al 2 de noviembre",
    "mensaje": "Responsable de la motivación, la voluntariedad, la pureza y la intención."
  },
  "46": {
    "angel": "Ariel",
    "imagen": "",
    "atributo": "Dios es mi Luz",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 3:00 p.m a 3:20 p.m",
    "se canaliza para": "Tener revelaciones en los sueños. tener nuevas ideas que iluminen los nuevos caminos. agradecer a Dios los bienes que nos envía",
    "color": "Rosado",
    "columna1": "Ariel",
    "por fecha de nac": "3 al  7 de noviembre",
    "mensaje": "Favorece nuestra clarividencia."
  },
  "47": {
    "angel": "Asaliah",
    "imagen": "",
    "atributo": "Dios que muestra la Verdad",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 3:20 p.m a 3:40 p.m",
    "se canaliza para": "Que nos conceda protección contra escándalos e inmoralidades. que la verdad brille en situaciones ocultas y nos guíe hacia un comportamiento adecuado. comprender las cosas divinas representadas en la naturaleza",
    "color": "Verde",
    "columna1": "Asaliah",
    "por fecha de nac": "8 al 12 de noviembre",
    "mensaje": "Te ayuda a descubrir la verdad que se oculta en las pequeñas cosas de la vida."
  },
  "48": {
    "angel": "Mihael",
    "imagen": "",
    "atributo": "Dios padre que Socorre",
    "planeta": "Sol",
    "coro angelical": "Principados",
    "aroma": "Mirra",
    "talisman": "Cuarzos",
    "ofrenda": "Dulces, Agua Marina",
    "don ser de luz": "Control del Medio Ambiente",
    "hora canalizacion": "de 3:40 p.m a 4:00 p.m",
    "se canaliza para": "Tener paz y armonía en la pareja. tener amistad y felicidad conyugal. invocar el socorro de dios. abrir la percepción",
    "color": "Magenta",
    "columna1": "Mihael",
    "por fecha de nac": "13 al 17 de noviembre",
    "mensaje": "Está encargado de traer armonía a las relaciones."
  },
  "49": {
    "angel": "Vehuel",
    "imagen": "",
    "atributo": "Dios Grandioso",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 4:00 p.m a 4:20 p.m",
    "se canaliza para": "Traer compresión mental. tener consuelo en las contrariedades. tener protección divina en la búsqueda de valores morales. impulsarnos al desarrollo espiritual",
    "color": "Gris",
    "columna1": "Vehuel",
    "por fecha de nac": "18 al 22 de noviembre",
    "mensaje": "Es el guía de todos lo que quieren conseguir la iluminación espiritual."
  },
  "50": {
    "angel": "Daniel",
    "imagen": "",
    "atributo": "Dios el Justo",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 4:20 p.m a 4:40 p.m",
    "se canaliza para": "Obtener misericordia divina. darnos remedio a todos los males. hacer renacer en nosotros nuevas esperanzas y alegría de vivir. ver el camino cuando estamos indecisos",
    "color": "Rosado",
    "columna1": "Daniel",
    "por fecha de nac": "23 al 27 de noviembre",
    "mensaje": "Es quien nos ayuda a desarrollar nuestra capacidad de comunicación."
  },
  "51": {
    "angel": "Hahasiah",
    "imagen": "",
    "atributo": "Dios Oculto",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 4:40 p.m a 5:00 p.m",
    "se canaliza para": "Curar enfermedades mentales. auxiliarnos en la revelación de misterios ocultos. elevar nuestra conciencia a Dios",
    "color": "Plata",
    "columna1": "Hahasiah",
    "por fecha de nac": "28 de noviembre al 2 de diciembre",
    "mensaje": "Sana con la energía cósmica y ayuda a médicos y enfermeras a cumplir con su labor."
  },
  "52": {
    "angel": "Imamiah",
    "imagen": "",
    "atributo": "Dios por encima de todo",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 5:00 p.m a 5:20 p.m",
    "se canaliza para": "Abandonar vicios y malas compañías. tener protección en los viajes. liberarnos de nuestras propias obsesiones. influenciar las ganancias monetarias provenientes del trabajo honesto",
    "color": "Plata",
    "columna1": "Imamiah",
    "por fecha de nac": "3 al 7 de diciembre",
    "mensaje": "Con él podemos sanar y reparar la mayoría de nuestros errores."
  },
  "53": {
    "angel": "Nanael",
    "imagen": "",
    "atributo": "Dios que hace caer a los orgullosos",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 5:20 p.m a 5:40 p.m",
    "se canaliza para": "Nuestro rejuvenecimiento físico e intelectual a través de aliviar patrones negativos. tener inspiración y apoyo material para grandes realizaciones",
    "color": "Violeta",
    "columna1": "Nanael",
    "por fecha de nac": "8 al 12 de diciembre",
    "mensaje": "Es el ángel de la comunicación espiritual en todas sus formas."
  },
  "54": {
    "angel": "Nithael",
    "imagen": "",
    "atributo": "Dios de los Cielos",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 5:40 p.m a 6:00 p.m",
    "se canaliza para": "Ayudarnos a conseguir de dios una vida larga. protegernos contra peligros y accidentes. tener estabilidad en el empleo y la conservación de los medios de subsistencia correctos",
    "color": "Amarillo",
    "columna1": "Nithael",
    "por fecha de nac": "13 al 17 de diciembre",
    "mensaje": "Representa la eterna juventud. Esto se debe a que está vinculado enormemente con el rejuvenecimiento."
  },
  "55": {
    "angel": "Mebahiah",
    "imagen": "",
    "atributo": "Dios Eterno",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 6:00 p.m a 6:20 p.m",
    "se canaliza para": "Tener fecundidad. proteger nuestra moral y religión. tener ayuda en cualquier entendimiento en que uno esté",
    "color": "Azul",
    "columna1": "Mebahiah",
    "por fecha de nac": "18 al 22 de diciembre",
    "mensaje": "Te aporta claridad y consuelo a tu vida."
  },
  "56": {
    "angel": "Poyel",
    "imagen": "",
    "atributo": "Dios que sostiene el Universo",
    "planeta": "Mercurio",
    "coro angelical": "Arcangeles",
    "aroma": "Frutas",
    "talisman": "Piedras de Colores",
    "ofrenda": "Flores de estacion, Lapizlazuli",
    "don ser de luz": "Control sobre las criaturas de la tierra",
    "hora canalizacion": "de 6:20 p.m a 6:40 p.m",
    "se canaliza para": "Tener fortuna en general. tener fama cuando difundimos grandes filosofías. ayudarnos a vencer demandas",
    "color": "Azul",
    "columna1": "Poyel",
    "por fecha de nac": "23 al 27 de diciembre",
    "mensaje": "Es el ángel de la fortuna y el apoyo."
  },
  "57": {
    "angel": "Nemamiah",
    "imagen": "",
    "atributo": "Dios Loable",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 6:40 p.m a 7:00 p.m",
    "se canaliza para": "Tener lucidez en los actos de la vida. concedernos prosperidad en todos los sectores. abrir canales para tener sueños proféticos. liberar a personas viciadas, para encaminarlas a una vida saludable. proteger y guiar a todos los que trabajan en causas justas",
    "color": "Rojo",
    "columna1": "Nemamiah",
    "por fecha de nac": "28 de diciembre al 1 de enero",
    "mensaje": "Es capaz de revelar la causa de tus problemas más profundos."
  },
  "58": {
    "angel": "Yeialel",
    "imagen": "",
    "atributo": "Dios que escucha los pedidos",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 7:00 p.m a 7:20 p.m",
    "se canaliza para": "Sanar la tristeza. ayudar en todo proceso de curación, especialmente los problemas de ojos. proteger a los que trabajan con metales",
    "color": "Rojo",
    "columna1": "Yeialel",
    "por fecha de nac": "2 al 6 de enero",
    "mensaje": "Te ayuda a desarrollar tus habilidades psíquicas como la clarividencia y lucidez."
  },
  "59": {
    "angel": "Harahel",
    "imagen": "",
    "atributo": "Dios Conocedor de todas las cosas",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 7:20 p.m a 7:40 p.m",
    "se canaliza para": "Atraer la fecundidad a las cosas estériles. encontrar objetos de valor perdidos. ayudarnos al pago de cuentas atrasadas. que los hijos sean amables y obedientes con sus padres. curar problemas en órganos reproductivos, principalmente en los femeninos. favorecer a los trabajadores de la bolsa, archivos, bibliotecas y coleccionistas",
    "color": "Dorado",
    "columna1": "Harahel",
    "por fecha de nac": "7 al 11 de enero",
    "mensaje": "Su principal objetivo es ayudarte a conseguir que tus sueños se hagan realidad."
  },
  "60": {
    "angel": "Mitzrael",
    "imagen": "",
    "atributo": "Dios alivio de los oprimidos",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 7:40 p.m a 8:00 p.m",
    "se canaliza para": "Curar problemas mentales. solucionar conflictos con uno mismo y con otros. atraer fidelidad de los subalternos. desarrollar talento y virtudes",
    "color": "Dorado",
    "columna1": "Mitzrael",
    "por fecha de nac": "12 al 16 de enero",
    "mensaje": "Corrige tus errores y te guía para que comprensas la importancia de la obediencia y la autoridad."
  },
  "61": {
    "angel": "Umabel",
    "imagen": "",
    "atributo": "Dios por encima de todo",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 8:00 p.m a 8:20 p.m",
    "se canaliza para": "Vivir una vida según las leyes divinas. hacer recapacitar a aquellos que se apartan de los mandamientos. mantener la armonía entre amigos",
    "color": "Verde",
    "columna1": "Umabel",
    "por fecha de nac": "17 al 21 de enero",
    "mensaje": " Te brinda una conciencia profunda de la vida, así como proporcionar concentración y comprensión cuando se requiera."
  },
  "62": {
    "angel": "Lah - hel",
    "imagen": "",
    "atributo": "Dios ser Supremo",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 8:20 p.m a 8:40 p.m",
    "se canaliza para": "Obtener sabiduría. poner en evidencia verdades ocultas. favorecer la comprensión y el entendimiento entre cónyuges. abandonar los placeres mundanos por los transcendentales. apaciguar la violencia del mundo",
    "color": "Verde",
    "columna1": "Lah - hel",
    "por fecha de nac": "22 al 26 de enero",
    "mensaje": "Impulsa tus pensamientos positivos, constructivos y te enseña a disfrutar la soledad y tranquilidad."
  },
  "63": {
    "angel": "Anauel",
    "imagen": "",
    "atributo": "Dios Infinitamente Bueno",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 8:40 p.m a 9:00 p.m",
    "se canaliza para": "Protección contra accidentes. curar enfermedades y mantener buena salud. tener prosperidad en la actividad profesional. ayudarnos a encontrar la verdadera espiritualidad y tener sabiduría",
    "color": "Gris",
    "columna1": "Anauel",
    "por fecha de nac": "27 de enero al 1 de febrero",
    "mensaje": " Permite que la comunicación y relación con otras personas resulten exitosas."
  },
  "64": {
    "angel": "Mehiel",
    "imagen": "",
    "atributo": "Dios que da Vida",
    "planeta": "Venus",
    "coro angelical": "Virtudes",
    "aroma": "Pino y Eucalipto",
    "talisman": "Plumas",
    "ofrenda": "Incienso, Sandalo, Rosas, Cuarzo Rosa",
    "don ser de luz": "Triunfos y Milagros",
    "hora canalizacion": "de 9:00 p.m a 9:20 p.m",
    "se canaliza para": "Protección de un comercio. reconfortarnos ante las adversidades. tener inspiración para obras literarias. protegernos contra accidentes de tránsito",
    "color": "Verde",
    "columna1": "Mehiel",
    "por fecha de nac": "2 al 6 de febrero",
    "mensaje": "Favorece la imaginación, la inteligencia y la comprensión. Es un gran aliado contra las energías y las fuerzas oscuras."
  },
  "65": {
    "angel": "Damabiah",
    "imagen": "",
    "atributo": "Dios fuente de Sabiduria",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 9:20 p.m a 9:40 p.m",
    "se canaliza para": "Darnos sabiduría y éxito en los negocios. protegernos en viajes por mar",
    "color": "Plata",
    "columna1": "Damabiah",
    "por fecha de nac": "7 al 11 de febrero",
    "mensaje": "Es el que entrega amor incondicional a todo aquel que acuda a él."
  },
  "66": {
    "angel": "Manakel",
    "imagen": "",
    "atributo": "Dios que mantiene las cosas",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 9:40 p.m a 10:00 p.m",
    "se canaliza para": "Calmar la cólera. proteger el sueño y combatir el insomnio. darnos inspiración para la música y la poesía",
    "color": "Plata",
    "columna1": "Manakel",
    "por fecha de nac": "12 al 16 de febrero",
    "mensaje": "Elimina miedos a través de la comprensión y transformación."
  },
  "67": {
    "angel": "Eyael",
    "imagen": "",
    "atributo": "Dios Alegría de los hombres",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 10:00 p.m a 10:20 p.m",
    "se canaliza para": "Ampliar la consciencia y la percepción. tener consuelo en las adversidades e injusticias. ayudarnos en la preservación de los bienes materiales obtenidos por trabajo. tener concentración en el estudio de filosofía mística y religión. ayudarnos en los cambios emocionales",
    "color": "Violeta",
    "columna1": "Eyael",
    "por fecha de nac": "17 al 21 de febrero",
    "mensaje": "Te orienta a tomar buenas decisiones y darte el soporte cuando sientas que todo está perdido."
  },
  "68": {
    "angel": "Habuhiah",
    "imagen": "",
    "atributo": "Dios Generoso",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 10:20 p.m a 10:40 p.m",
    "se canaliza para": "Tener fertilidad en la tierra. tener fertilidad en las parejas. proteger la salud y tener curación en general",
    "color": "Violeta",
    "columna1": "Habuhiah",
    "por fecha de nac": "22 al 26 de febrero",
    "mensaje": "Es el patrón de las terapias médicas, así como de los tratamientos espirituales o metafísicos."
  },
  "69": {
    "angel": "Rochel",
    "imagen": "",
    "atributo": "Dios que todo lo ve",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 10:40 p.m a 11:00 p.m",
    "se canaliza para": "Abrir la percepción para encontrar objetos perdidos o robados. influir sobre la fama y fortuna de abogados y magistrados",
    "color": "Azul",
    "columna1": "Rochel",
    "por fecha de nac": "27 de febrero al 3 de marzo",
    "mensaje": "Es el encargado de otorgar a cada persona lo que se merece, es el símbolo de la justicia y lo justo."
  },
  "70": {
    "angel": "Jabamiah",
    "imagen": "",
    "atributo": "Dios creador de todas las cosas",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 11:00 p.m a 11:20 p.m",
    "se canaliza para": "Darnos confianza y optimismo. cambiar nuestros hábitos de pensamiento. ayudarnos en la desintoxicación de drogas y alcohol",
    "color": "Azul",
    "columna1": "Jabamiah",
    "por fecha de nac": "4 al 8 demarzo",
    "mensaje": "Entrega energía curativa a tu vida. Tiene la capacidad de regenerar, sanar, revitalizar y restaurar la armonía."
  },
  "71": {
    "angel": "Haiaiel",
    "imagen": "",
    "atributo": "Dios nuestro del universo",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 11:20 p.m a 11:40 p.m",
    "se canaliza para": "Tener coraje y valentía para enfrentar peligros. liberarnos de vínculos con personas que nos quieren oprimir. sentirnos en paz y tener fuerza, valentía, talento y seguridad en todas las actividades",
    "color": "Violeta",
    "columna1": "Haiaiel",
    "por fecha de nac": "9 al 13 de marzo",
    "mensaje": "Nos brinda protección divina y nos ayuda a tomar decisiones justas y correctas."
  },
  "72": {
    "angel": "Mumiah",
    "imagen": "",
    "atributo": "Dios fin de todas las cosas",
    "planeta": "Luna",
    "coro angelical": "Guardianes",
    "aroma": "Flores Silvestres, Frutas de estacion e Incienso",
    "talisman": "Gemas Opacas",
    "ofrenda": "Frutas frescas, Agatas, Cuarzo Cristal",
    "don ser de luz": "Voluntad Divina",
    "hora canalizacion": "de 11:40 p.m a 12:00 a.m",
    "se canaliza para": "Proteger a pobres y sufrientes. protegernos contra operaciones mágicas de las cuales no tenemos conocimiento. ayudarnos a tener flexibilidad en lo emocional. ayudarnos a ver nuestras trabas emocionales",
    "color": "Naranja",
    "columna1": "Mumiah",
    "por fecha de nac": "14 al 19 de marzo",
    "mensaje": "Ayuda a terminar las tareas difíciles y nos regala la energía necesaria para empezar otras nuevas."
  }
};