export const tablaMentor = {
  "domingo": {
    "mentor": "Miguel",
    "colorMentor":"#3B82F6",
    "colorNombreMentor":"Azul",
    "angelGuia": "Miguel",
    "colorGuia": "#3B82F6",
    "colorNombreGuia":"Azul",
    "angelDia": "Miguel",    
    "colorDia": "#3B82F6",
    "colorNombreDia":"Azul",
    "significado":"Protección y fortaleza",
    "codigoSagrado": "613",
    "atributo": "Quien como Dios",
    "planeta": "Sol",
    "gracia": "Voluntad, valor, fe, fuerza,poder, protección y liberación",
    "gemas": "Turmalina negra, cuarzo azul y lapislázuli",
    "aroma": "Ruda",
    "seCanalizaPara": "Protección, exorcizar tentaciones",
    "don": "Control sobre las criaturas de la tierra"
  },
  "lunes": {
    "mentor": "Gabriel",
    "colorMentor":"#FFFFFF",
    "colorNombreMentor":"Blanco",
    "angelGuia": "Jofiel",
    "colorGuia": "#F59E0B",
    "colorNombreGuia":"Ambar",
    "angelDia": "Gabriel",    
    "colorDia": "#FFFFFF",
    "colorNombreDia":"Blanco",
    "significado":"Sabiduría y Paz",
    "codigoSagrado": "881,581",
    "atributo": "La Fuerza de Dios",
    "planeta": "Luna",
    "gracia": "Orientación, renovación y guia espiritual",
    "gemas": "Cuarzo Blanco y piedra Luna",
    "aroma": "Sándalo",
    "seCanalizaPara": "Cultivar la inspiración, la creatividad, la comiunicación",
    "don": "Control sobre las criaturas de la tierra"
  },
  "martes": {
    "mentor": "Chamuel",
    "colorMentor":"#EC4899",
    "colorNombreMentor":"Rosado",
    "angelGuia": "Chamuel",
    "colorGuia": "#EC4899",
    "colorNombreGuia":"Rosado",
    "angelDia": "Chamuel",    
    "colorDia": "#EC4899",
    "colorNombreDia":"Rosado",
    "significado":"Amor divino y gratitud",
    "codigoSagrado": "725,125",
    "atributo": "El que va con Dios",
    "planeta": "Venus",
    "gracia": "Amor y Compasióm universal",
    "gemas": "Cuarzo rosa y rodocrosita",
    "aroma": "Rosa y Miel",
    "seCanalizaPara": "Cultivar el amor propio, protección contra todo mal",
    "don": "Control sobre las criaturas de la tierra"
  },
  "miércoles": {
    "mentor": "Rafael",
    "colorMentor":"#22C55E",
    "colorNombreMentor":"Verde",
    "angelGuia": "Gabriel",
    "colorGuia": "#FFFFFF",
    "colorNombreGuia":"Blanco",
    "angelDia": "Rafael",    
    "colorDia": "#22C55E",
    "colorNombreDia":"Verde",
    "significado":"Protección y fortaleza",
    "codigoSagrado": "29,2129,1577",
    "atributo": "El que Dios Sana",
    "planeta": "Mercurio",
    "gracia": "Sanación, curación, don de sanación,consuelo u olvido de penas",
    "gemas": "Cuarzo verde, aventurina, malaquita y jade",
    "aroma": "Jazmin",
    "seCanalizaPara": "Sanación en todos los niveles",
    "don": "Control sobre las criaturas de la tierra"
  },
  "jueves": {
    "mentor": "Zadquiel",
    "colorMentor":"#9333EA",
    "colorNombreMentor":"Violeta",
    "angelGuia": "Rafael",
    "colorGuia": "#22C55E",
    "colorNombreGuia":"Verde",
    "angelDia": "Sadchiel",    
    "colorDia": "#3B82F6",
    "colorNombreDia":"Azul",
    "significado":"Curación, concentración y verdad",
    "codigoSagrado": "389",
    "atributo": "Justicia de Dios",
    "planeta": "Júpiter",
    "gracia": "Transmutacion, perdon y don de la intuicion",
    "gemas": "Amatista, kunsita y sugilita",
    "aroma": "Lavanda",
    "seCanalizaPara": "Liberación espiritual, capacidad de perdonar",
    "don": "Control sobre las criaturas de la tierra"
  },
  "viernes": {
    "mentor": "Anael",
    "colorMentor":"#EC4899",
    "colorNombreMentor":"Magenta",
    "angelGuia": "Uriel",
    "colorGuia": "#EF4444",
    "colorNombreGuia":"Rojo Brillante",
    "angelDia": "Anael",    
    "colorDia": "#EC4899",
    "colorNombreDia":"Magenta",
    "significado":"Suministro de dinero y grecia divina",
    "codigoSagrado": "991",
    "atributo": "Gloria o Gracia de Dios",
    "planeta": "Venus",
    "gracia": "Cultiva el amor propio",
    "gemas": "Esmeralda",
    "aroma": "Azahar",
    "seCanalizaPara": "Paz, serenidad, armonía",
    "don": "Voluntad Divina"
  },
  "sábado": {
    "mentor": "Cassiel",
    "colorMentor":"#6366F1",
    "colorNombreMentor":"Azul",
    "angelGuia": "Zadquiel",
    "colorGuia": "#9333EA",
    "colorNombreGuia":"Violeta",
    "angelDia": "Cassiel",    
    "colorDia": "#6366F1",
    "colorNombreDia":"Azul",
    "significado":"Invocación, transmutar y liberar",
    "codigoSagrado": "781",
    "atributo": "Cubierta de Dios",
    "planeta": "Saturno",
    "gracia": "Temperanza",
    "gemas": "Onix negro",
    "aroma": "Mejorana",
    "seCanalizaPara": "Claridad mental, transmutar",
    "don": "Voluntad Divina"
  }
};